require('plugins')
require('lsp').setup()
require('mappings')
require('nvim-cmp-cfg')
require('rust-tools-cfg')
require('telescope-cfg')
require('treesitter-cfg')
--require('trouble-cfg')
require('lualine-cfg')
--require('nvim-lsp-installer-cfg')

require('nvim-tree').setup()
