require('plugins')
require('lsp').setup()
require('nvim-cmp-cfg')
require('mappings')
require('rust-tools-cfg')
require('telescope-cfg')
require('treesitter-cfg')
require('nvim-tree-cfg')
require('trouble-cfg')
require('lualine-cfg')

-- require('nvim-tree').setup()
